//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDeath
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ActNo { get; set; }
        public string ActPage { get; set; }
        public string ActYear { get; set; }
        public string DeathPlace { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public string DeathName { get; set; }
        public string DeathSurname { get; set; }
        public Nullable<int> DeathPersonId { get; set; }
        public Nullable<System.DateTime> DeathPersonBirthDate { get; set; }
        public string DeathPersonAge { get; set; }
        public Nullable<short> DeathPersonFaith { get; set; }
        public string DeathMotherName { get; set; }
        public string DeathMotherSurname { get; set; }
        public Nullable<int> DeathMotherId { get; set; }
        public string DeathFatherName { get; set; }
        public string DeathFatherSurname { get; set; }
        public Nullable<int> DeathFatherId { get; set; }
        public string DeathSpouseName { get; set; }
        public string DeathSpouseSurname { get; set; }
        public Nullable<int> DeathSpouseId { get; set; }
        public string SacramentDetails { get; set; }
        public Nullable<System.DateTime> FuneralDate { get; set; }
        public string FuneralPlace { get; set; }
        public string Remarks { get; set; }
        public string PastorNameSurname { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<int> FkPerson { get; set; }
        public Nullable<int> FkMother { get; set; }
        public Nullable<int> FkFather { get; set; }
        public Nullable<int> FkSpouse { get; set; }
        public Nullable<int> YearBirth { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
