//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookMarriage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ActNo { get; set; }
        public string ActPage { get; set; }
        public string ActYear { get; set; }
        public string WeddingPlace { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public string WifeName { get; set; }
        public string WifeSurname { get; set; }
        public Nullable<System.DateTime> WifeBirthDate { get; set; }
        public Nullable<int> WifeBirthYear { get; set; }
        public string WifeBirthPlace { get; set; }
        public Nullable<short> WifeFaith { get; set; }
        public Nullable<System.DateTime> WifeBaptismDate { get; set; }
        public Nullable<int> WifeYearBaptism { get; set; }
        public string WifeBaptismPlace { get; set; }
        public Nullable<short> WifeMaritalStatus { get; set; }
        public string WifeMotherName { get; set; }
        public string WifeMotherSurname { get; set; }
        public string WifeFatherName { get; set; }
        public string WifeFatherSurname { get; set; }
        public string HusbandName { get; set; }
        public string HusbandSurname { get; set; }
        public Nullable<System.DateTime> HusbandBirthDate { get; set; }
        public Nullable<int> HusbandBirthYear { get; set; }
        public string HusbandBirthPlace { get; set; }
        public Nullable<short> HusbandFaith { get; set; }
        public Nullable<System.DateTime> HusbandBaptismDate { get; set; }
        public Nullable<int> HusbandYearBaptism { get; set; }
        public string HusbandBaptismPlace { get; set; }
        public Nullable<short> HusbandMaritalStatus { get; set; }
        public string HusbandMotherName { get; set; }
        public string HusbandMotherSurname { get; set; }
        public string HusbandFatherName { get; set; }
        public string HusbandFatherSurname { get; set; }
        public Nullable<System.DateTime> WeddingCivilDate { get; set; }
        public string WeddingCivilAuthority { get; set; }
        public string PastorNameSurname { get; set; }
        public string WitnessWomanName { get; set; }
        public string WitnessWomanSurname { get; set; }
        public string WitnessManName { get; set; }
        public string WitnessManSurname { get; set; }
        public string WitnessWomanAge { get; set; }
        public string WitnessWomanAddress { get; set; }
        public string WitnessManAge { get; set; }
        public string WitnessManAddress { get; set; }
        public string WeddingProtocolNumber { get; set; }
        public string SacramentDetails { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<int> FkWife { get; set; }
        public Nullable<int> FkHusband { get; set; }
        public Nullable<int> FkWifeMother { get; set; }
        public Nullable<int> FkWifeFather { get; set; }
        public Nullable<int> FkHusbandMother { get; set; }
        public Nullable<int> FkHusbandFather { get; set; }
        public Nullable<int> FkWitnessWoman { get; set; }
        public Nullable<int> FkWitnessMan { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
