//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookConfirmation
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string ActNo { get; set; }
        public string ActPage { get; set; }
        public string ActYear { get; set; }
        public string ConfirmationPlace { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public string ConfirmationPersonName { get; set; }
        public string ConfirmationPersonSurname { get; set; }
        public string ConfirmationName { get; set; }
        public Nullable<System.DateTime> BaptismDate { get; set; }
        public Nullable<int> YearBaptism { get; set; }
        public Nullable<int> YearConfirmation { get; set; }
        public string SacramentDetails { get; set; }
        public string Remarks { get; set; }
        public string PastorNameSurname { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<int> FkPerson { get; set; }
        public string ParishName { get; set; }
        public Nullable<int> FkWitness { get; set; }
        public string WitnessName { get; set; }
        public string WitnessSurname { get; set; }
        public string BaptismPlace { get; set; }
        public Nullable<short> PersonSex { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
