//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarolFamily
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> FkFamily { get; set; }
        public Nullable<int> FkCarol { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MoneyAmount { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> FkUser { get; set; }
    }
}
