//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carol
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string AddressBand { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<int> FkPriest { get; set; }
        public Nullable<System.DateTime> DateCarol { get; set; }
        public string Description { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
