//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cemetery
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string City { get; set; }
        public string Code { get; set; }
        public string Address { get; set; }
        public System.DateTime DateBuilded { get; set; }
        public Nullable<int> FkUser { get; set; }
        public string CemeteryName { get; set; }
        public string LocationAttributeOne { get; set; }
        public string LocationAttributeTwo { get; set; }
        public string LocationAttributeThree { get; set; }
        public string LocationAttributeFour { get; set; }
        public string Description { get; set; }
    }
}
