//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class CemeteryGrave
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string RegNumber { get; set; }
        public string Owner { get; set; }
        public Nullable<int> FkCemetery { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateExpired { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<short> Attribute { get; set; }
        public Nullable<bool> BoolHistoric { get; set; }
        public string HistoricRecordDescription { get; set; }
        public Nullable<bool> BoolNoFee { get; set; }
        public string PictureFile { get; set; }
        public Nullable<int> FkUser { get; set; }
        public string LocationAttributeOne { get; set; }
        public string LocationAttributeTwo { get; set; }
        public string LocationAttributeThree { get; set; }
        public string LocationAttributeFour { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
        public Nullable<int> FkGraveCoordinate { get; set; }
        public Nullable<bool> IsReserved { get; set; }
    }
}
