//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string EventTitle { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<short> EventType { get; set; }
        public Nullable<short> EventCategory { get; set; }
        public string EventRemarks { get; set; }
        public Nullable<int> FkUser { get; set; }
        public string IdMembers { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
