//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<short> DocumentType { get; set; }
        public Nullable<short> DocumentCategory { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
