//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CmentarioDBEntities : DbContext
    {
        public CmentarioDBEntities()
            : base("name=ParafisDBTestoweEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cemetery> Cemetery { get; set; }
        public virtual DbSet<CemeteryGrave> CemeteryGrave { get; set; }
        public virtual DbSet<CemeteryGravePayment> CemeteryGravePayment { get; set; }
        public virtual DbSet<CemeteryGravePerson> CemeteryGravePerson { get; set; }
        public virtual DbSet<CemeteryGravePhoto> CemeteryGravePhoto { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<VGravePersonDetail> VGravePersonDetail { get; set; }
        public virtual DbSet<GraveCoordinate> GraveCoordinate { get; set; }
        public virtual DbSet<VUnassignedCords> VUnassignedCords { get; set; }
    }
}
