//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VGravePersonDetail
    {
        public int Id { get; set; }
        public Nullable<int> FkGrave { get; set; }
        public Nullable<int> FkPerson { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<System.DateTime> DateDeath { get; set; }
        public Nullable<int> YearBirth { get; set; }
        public Nullable<int> YearDeath { get; set; }
        public string LocationAttributeOne { get; set; }
        public string LocationAttributeTwo { get; set; }
        public string LocationAttributeThree { get; set; }
        public string LocationAttributeFour { get; set; }
    }
}
