//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CemeteryWeb.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitSickPerson
    {
        public int Id { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<int> FkPerson { get; set; }
        public Nullable<int> FkUser { get; set; }
        public Nullable<System.DateTime> DateVisit { get; set; }
        public Nullable<System.DateTime> DateNextVisit { get; set; }
        public Nullable<int> FkPrist { get; set; }
        public string Description { get; set; }
        public Nullable<bool> BoolCommunion { get; set; }
        public Nullable<bool> BoolVisitTookPlace { get; set; }
        public Nullable<bool> BoolConfession { get; set; }
        public Nullable<bool> BoolAnointing { get; set; }
        public Nullable<bool> IsForVerification { get; set; }
    }
}
